sudo: required 
language: generic

services:
  - docker

before_install:
  - docker build -t alessandromacri/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alessandromacri/client-test npm test

# Production version dopo l'esecuzione dei test
after_success: 
  - docker build -t alessandromacri/multi-client ./client
  - docker build -t alessandromacri/multi-nginx ./nginx
  - docker build -t alessandromacri/multi-api ./api
  - docker build -t alessandromacri/multi-worker ./worker
  # Signin to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image in docker HUB
  - docker push alessandromacri/multi-client
  - docker push alessandromacri/multi-nginx
  - docker push alessandromacri/multi-api
  - docker push alessandromacri/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-887002784570"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY