sudo: required 
services:
  - docker

before_install:
  - docker build -t alessandromacri/client-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true alessandromacri/client-test npm test

# Production version dopo l'esecuzione dei test
after_success: 
  - docker build -t alessandromacri/multi-client ./client
  - docker build -t alessandromacri/multi-nginx ./nginx
  - docker build -t alessandromacri/multi-api ./api
  - docker build -t alessandromacri/multi-worker ./worker
  # Signin to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image in docker HUB
  - docker push alessandromacri/multi-client
  - docker push alessandromacri/multi-nginx
  - docker push alessandromacri/multi-api
  - docker push alessandromacri/multi-worker